service: serverless-node-graphql-db-email 

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
custom:
  secrets: ${file(secrets.json)}
  
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: eu-west-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    FROM_EMAIL: ${self:custom.secrets.FROM_EMAIL}
  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: get
          cors: true
